// 获取精品歌单
var types = {
    SET_TOP_PLAY: 'SET_TOP_PLAY',

    SET_MUSIC_DATA: 'SET_MUSIC_DATA',

    SET_MUSIC_LIST_DATA: 'SET_MUSIC_LIST_DATA',

    SET_LYRIC: 'SET_LYRIC',

    SET_HOT_COMMENT: 'SET_HOT_COMMENT',

    SET_PLAYURL: 'SET_PLAYURL',

    SET_LISTDETAIL: 'SET_LISTDETAIL'
}

export default types
